# Generated by Django 4.1.4 on 2022-12-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_contact', models.CharField(max_length=10)),
                ('emp_role', models.CharField(max_length=200)),
                ('emp_salary', models.IntegerField()),
            ],
        ),
    ]
